// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cynzueqpbgiimnpvqqya.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN5bnp1ZXFwYmdpaW1ucHZxcXlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAwNTk0MTYsImV4cCI6MjA4NTYzNTQxNn0.-Ie30yVgDaIkx0UIwQmJQMXkQIOs3JNYlXdcFjJD0O0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});